const COUNTRY_CODES: Record<string, string> = {
  // CONCACAF
  USA: "US",
  Canada: "CA",
  Mexico: "MX",
  Panama: "PA",
  Honduras: "HN",
  "Costa Rica": "CR",
  Jamaica: "JM",
  "El Salvador": "SV",
  Guatemala: "GT",
  Cuba: "CU",
  Haiti: "HT",
  "Trinidad and Tobago": "TT",
  Curaçao: "CW",
  Curacao: "CW",

  // CONMEBOL
  Argentina: "AR",
  Brazil: "BR",
  Colombia: "CO",
  Ecuador: "EC",
  Uruguay: "UY",
  Paraguay: "PY",
  Chile: "CL",
  Bolivia: "BO",
  Peru: "PE",
  Venezuela: "VE",

  // UEFA
  Germany: "DE",
  France: "FR",
  Spain: "ES",
  England: "GB",
  Portugal: "PT",
  Netherlands: "NL",
  Belgium: "BE",
  Italy: "IT",
  Croatia: "HR",
  Denmark: "DK",
  Switzerland: "CH",
  Austria: "AT",
  Poland: "PL",
  Serbia: "RS",
  Romania: "RO",
  "Czech Republic": "CZ",
  Czechia: "CZ",
  Hungary: "HU",
  Scotland: "GB",
  Wales: "GB",
  Slovakia: "SK",
  Slovenia: "SI",
  Turkey: "TR",
  Ukraine: "UA",
  Greece: "GR",
  Norway: "NO",
  Sweden: "SE",
  Finland: "FI",
  Albania: "AL",
  Georgia: "GE",
  Bosnia: "BA",
  Iceland: "IS",
  "Northern Ireland": "GB",
  Luxembourg: "LU",
  Kosovo: "XK",

  // CAF
  Morocco: "MA",
  Senegal: "SN",
  Nigeria: "NG",
  Egypt: "EG",
  "Ivory Coast": "CI",
  Cameroon: "CM",
  Ghana: "GH",
  Algeria: "DZ",
  Tunisia: "TN",
  "South Africa": "ZA",
  Mali: "ML",
  "DR Congo": "CD",
  "Congo DR": "CD",
  "Congo, DR": "CD",
  Tanzania: "TZ",
  Zambia: "ZM",
  Angola: "AO",
  Mozambique: "MZ",
  Uganda: "UG",
  "Burkina Faso": "BF",
  Gabon: "GA",
  "Cape Verde": "CV",
  "Cabo Verde": "CV",

  // AFC
  Japan: "JP",
  "South Korea": "KR",
  Iran: "IR",
  "Saudi Arabia": "SA",
  Australia: "AU",
  Qatar: "QA",
  Uzbekistan: "UZ",
  Jordan: "JO",
  Iraq: "IQ",
  Oman: "OM",
  China: "CN",
  Indonesia: "ID",
  Bahrain: "BH",
  UAE: "AE",
  Kuwait: "KW",
  Syria: "SY",

  // OFC
  "New Zealand": "NZ",
}

export function getCountryCode(teamName: string): string | undefined {
  return COUNTRY_CODES[teamName]
}

export const ALL_TEAMS = Object.keys(COUNTRY_CODES).sort((a, b) => a.localeCompare(b))
